"""Nginx config renderer."""

from __future__ import annotations

from local_llm_setup.models.config import SetupConfig


def render_nginx_conf(config: SetupConfig) -> str:
    ngx = config.nginx
    primary = config.frameworks[0]
    upstream_name = "llm_backend"
    upstream_host = primary.framework.value.replace(".", "")
    upstream_port = primary.port

    api_key_block = ""
    if ngx.api_key_auth:
        api_key_block = """
        # API key auth
        if ($api_key_valid = 0) {
            return 401 '{"error": "invalid or missing API key"}';
        }
"""

    cors_block = ""
    if ngx.enable_cors:
        cors_block = """
            add_header Access-Control-Allow-Origin * always;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
            add_header Access-Control-Allow-Headers "Authorization, Content-Type, X-API-Key" always;
            if ($request_method = OPTIONS) {
                return 204;
            }
"""

    map_block = ""
    if ngx.api_key_auth:
        map_block = """
map $http_x_api_key $api_key_valid {
    default 0;
    include /etc/nginx/api_keys.map;
}
"""

    return f"""# Generated by local-llm-setup
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {{
    worker_connections 1024;
}}

http {{
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    client_max_body_size {ngx.client_max_body_size};
{map_block}
    upstream {upstream_name} {{
        server {upstream_host}:{upstream_port};
        keepalive 32;
    }}

    server {{
        listen 80;
        server_name {ngx.server_name};

        location / {{
            proxy_pass http://{upstream_name};
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Connection "";
            proxy_read_timeout {ngx.proxy_read_timeout};
            proxy_send_timeout {ngx.proxy_read_timeout};
{cors_block}{api_key_block}
        }}

        location /health {{
            access_log off;
            return 200 "ok\\n";
            add_header Content-Type text/plain;
        }}
    }}
}}
"""


def render_api_keys_map(config: SetupConfig) -> str:
    lines = ["# Generated by local-llm-setup — key label comments"]
    for entry in config.nginx.api_keys:
        lines.append(f'"{entry.key}" 1;  # {entry.label}')
    return "\n".join(lines) + "\n"
