"""Nginx config renderer."""

from __future__ import annotations

from local_llm_setup.models.config import FrameworkConfig, SetupConfig


def _service_name(fc: FrameworkConfig) -> str:
    return fc.framework.value.replace(".", "")


def _proxy_headers(ngx_read_timeout: str) -> str:
    return f"""
            proxy_http_version 1.1;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_cache off;
            proxy_read_timeout {ngx_read_timeout};
            proxy_send_timeout {ngx_read_timeout};
"""


def _location_block(
    *,
    path: str,
    upstream_host: str,
    upstream_port: int,
    ngx,
    cors_block: str,
    api_key_block: str,
    use_named_upstream: bool,
    upstream_name: str,
) -> str:
    target = f"http://{upstream_name}" if use_named_upstream else f"http://{upstream_host}:{upstream_port}"
    trailing = "/" if path != "/" else ""
    return f"""
        location {path} {{
            proxy_pass {target}{trailing};
{_proxy_headers(ngx.proxy_read_timeout)}{cors_block}{api_key_block}
        }}"""


def render_nginx_conf(config: SetupConfig) -> str:
    ngx = config.nginx
    frameworks = config.frameworks

    api_key_block = ""
    if ngx.api_key_auth:
        api_key_block = """
            if ($api_key_valid = 0) {
                return 401 '{"error": "invalid or missing API key"}';
            }
"""

    cors_block = ""
    if ngx.enable_cors:
        cors_block = """
            add_header Access-Control-Allow-Origin * always;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
            add_header Access-Control-Allow-Headers "Authorization, Content-Type, X-API-Key" always;

            if ($request_method = OPTIONS) {
                add_header Access-Control-Allow-Origin * always;
                add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
                add_header Access-Control-Allow-Headers "Authorization, Content-Type, X-API-Key" always;
                add_header Content-Length 0;
                return 204;
            }
"""

    map_block = ""
    if ngx.api_key_auth:
        map_block = """
map $http_x_api_key $api_key_valid {
    default 0;
    include /etc/nginx/api_keys.map;
}
"""

    server_name = ngx.server_name if ngx.server_name not in ("localhost", "127.0.0.1") else "_"

    upstream_blocks = ""
    location_blocks = ""

    if len(frameworks) == 1:
        primary = frameworks[0]
        upstream_name = "llm_backend"
        upstream_host = _service_name(primary)
        upstream_blocks = f"""
    upstream {upstream_name} {{
        server {upstream_host}:{primary.port};
        keepalive 32;
    }}
"""
        location_blocks = _location_block(
            path="/",
            upstream_host=upstream_host,
            upstream_port=primary.port,
            ngx=ngx,
            cors_block=cors_block,
            api_key_block=api_key_block,
            use_named_upstream=True,
            upstream_name=upstream_name,
        )
    else:
        for fc in frameworks:
            prefix = f"/{fc.framework.value}/"
            location_blocks += _location_block(
                path=prefix,
                upstream_host=_service_name(fc),
                upstream_port=fc.port,
                ngx=ngx,
                cors_block=cors_block,
                api_key_block=api_key_block,
                use_named_upstream=False,
                upstream_name="",
            )
        primary = frameworks[0]
        location_blocks += _location_block(
            path="/",
            upstream_host=_service_name(primary),
            upstream_port=primary.port,
            ngx=ngx,
            cors_block=cors_block,
            api_key_block=api_key_block,
            use_named_upstream=False,
            upstream_name="",
        )

    return f"""# Generated by local-llm-setup
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {{
    worker_connections 1024;
}}

http {{
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    client_max_body_size {ngx.client_max_body_size};

    map $http_upgrade $connection_upgrade {{
        default upgrade;
        ''      close;
    }}
{map_block}{upstream_blocks}
    server {{
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name {server_name};

        location /health {{
            access_log off;
            add_header Content-Type text/plain always;
            return 200 "ok\\n";
        }}
{location_blocks}
    }}
}}
"""


def render_api_keys_map(config: SetupConfig) -> str:
    lines = ["# Generated by local-llm-setup — key label comments"]
    for entry in config.nginx.api_keys:
        lines.append(f'"{entry.key}" 1;  # {entry.label}')
    return "\n".join(lines) + "\n"
